#ifndef TYPED_IMAGE_NODE_H
#define TYPED_IMAGE_NODE_H

#include "App/ImageNode.hpp"
#include "ImageOperation/ImageAttributes.hpp"

MAKE_IMAGE_NODE(ColorData)
MAKE_IMAGE_NODE(Construct3fData)
MAKE_IMAGE_NODE(Split3fData)
MAKE_IMAGE_NODE(ImageAddData)
MAKE_IMAGE_NODE(ImageSubData)
MAKE_IMAGE_NODE(ImageMultData)
MAKE_IMAGE_NODE(ImageDivData)
MAKE_IMAGE_NODE(ImageMixData)
MAKE_IMAGE_NODE(ImageClampData)
MAKE_IMAGE_NODE(ImageDotData)
MAKE_IMAGE_NODE(ImageCrossData)
MAKE_IMAGE_NODE(ImageStepData)
MAKE_IMAGE_NODE(ImagePowData)
MAKE_IMAGE_NODE(ImageSqrtData)
MAKE_IMAGE_NODE(ImageAbsData)
MAKE_IMAGE_NODE(ImageSinData)
MAKE_IMAGE_NODE(ImageCosData)
MAKE_IMAGE_NODE(ImageTanData)
MAKE_IMAGE_NODE(ImageModData)
MAKE_IMAGE_NODE(ImageExpData)
MAKE_IMAGE_NODE(ImageLogData)
MAKE_IMAGE_NODE(ImageMinData)
MAKE_IMAGE_NODE(ImageMaxData)
MAKE_IMAGE_NODE(WhiteNoiseData)
MAKE_IMAGE_NODE(ValueNoiseData)
MAKE_IMAGE_NODE(GradientNoiseData)
MAKE_IMAGE_NODE(SimplexNoiseData)
MAKE_IMAGE_NODE(VoronoiNoiseData)
MAKE_IMAGE_NODE(MandelbrotData)
MAKE_IMAGE_NODE(DynamicsData)
MAKE_IMAGE_NODE(ImageOutput)
MAKE_IMAGE_NODE(UvDistortionData)
MAKE_IMAGE_NODE(BlurFilterData)
MAKE_IMAGE_NODE(SharpenFilterData)
MAKE_IMAGE_NODE(MorphoFilterData)
MAKE_IMAGE_NODE(BumpToNormalData)
MAKE_IMAGE_NODE(UvMappingData)
MAKE_IMAGE_NODE(UvInputData)
MAKE_IMAGE_NODE(SphericalCoordData)
MAKE_IMAGE_NODE(DirectionalSignalData)
MAKE_IMAGE_NODE(RadialSignalData)
MAKE_IMAGE_NODE(TimeData)


#endif // TYPED_IMAGE_NODE_H
