#ifndef QUASAR_BELL_VERSION_HPP
#define QUASAR_BELL_VERSION_HPP

#define QB_VERSION_MAJOR 4
#define QB_VERSION_MINOR 1
#define QB_VERSION QB_VERSION_MAJOR+QB_VERSION_MINOR*1e-1

#endif // QUASAR_BELL_VERSION_HPP